# Staging Overlay
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pharma-staging

resources:
  - ../../base

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: pharma-transport-config
    behavior: merge
    literals:
      - LOG_LEVEL=debug
      - WEB_CONCURRENCY=2

images:
  - name: pharma-transport
    newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/pharma-transport
